# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build with Go'
    strategy:
      matrix:
        go_1_13:
          go_version: '1.13'
        go_1_14:
          go_version: '1.14'
        go_1_15:
          go_version: '1.15'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - name: GOBIN
      value: '$(GOPATH)/bin' # Go binaries path
    - name: GOPATH
      value: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    - name: modulePath
      value: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
    - group: 'build-terraform-provider-databricks'
    steps:
    - task: GoTool@0
      displayName: Install Go $(go_version)
      inputs:
        version: $(go_version)
    - script: |
        go version
        pwd
        mkdir -p '$(GOBIN)'
        mkdir -p '$(GOPATH)/pkg'
        mkdir -p '$(modulePath)'
        shopt -s extglob
        shopt -s dotglob
        mv !(gopath) '$(modulePath)'
        echo '##vso[task.prependpath]$(GOBIN)'
        echo '##vso[task.prependpath]$(GOROOT)/bin'
      displayName: 'Set up the Go workspace'
    - script: |
        go version
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        curl -sSL "https://github.com/gotestyourself/gotestsum/releases/download/v0.4.2/gotestsum_0.4.2_linux_amd64.tar.gz" | sudo tar -xz -C /usr/local/bin gotestsum
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0
        curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

        go get github.com/go-delve/delve/cmd/dlv@v1.3.2
        go get golang.org/x/tools/gopls@v0.4.1
        go get golang.org/x/tools/cmd/goimports
        go get gotest.tools/gotestsum@v0.4.2
        go get github.com/acroca/go-symbols@v0.1.1 && go get github.com/ramya-rao-a/go-outline@7182a932836a71948db4a81991a494751eccfe77
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sed 's/tar -/tar --no-same-owner -/g' | sh -s -- -b $(go env GOPATH)/bin
        go get github.com/axw/gocov/gocov
        go get github.com/AlekSi/gocov-xml
      workingDirectory: $(modulePath)
      displayName: Get dependencies & tools
    - script: |
        go version
        go build -mod vendor -v -ldflags="-X 'common.version=$(git describe --long --always | sed 's/v//')'" -o terraform-provider-databricks .
      workingDirectory: $(modulePath)
      displayName: 'Build'
    - script: |
        go version
        gotestsum --junitfile=test-report.xml --raw-command go test -v -json -short -coverprofile=cover.out ./...
        gocov convert cover.out | gocov-xml > coverage-report.xml
      workingDirectory: $(modulePath)
      displayName: 'Tests & Coverage'
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud Olivier Delmotte' # '$(SonarConnection)'
        organization: '$(SonarOrganization)'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '$(SonarKey)'
        cliProjectName: '$(SonarProjectName)'
        cliProjectVersion: '$(build.buildnumber)'
        cliSources: '$(modulePath)'
        extraProperties: |
          sonar.junit.reportsPath=test-report.xml
          sonar.java.coveragePlugin=jacoco
          sonar.jacoco.reportPath=coverage-report.xml
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
    - powershell: |
        gci env:
      displayName: Go setup debug
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(modulePath)/test-report.xml'
        testRunTitle: 'Unit Tests on $(go_version)'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(modulePath)/coverage-report.xml'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(modulePath)/terraform-provider-databricks'
        artifact: 'gopack-$(go_version)'
        publishLocation: 'pipeline'
- stage: TestOnAzure
  dependsOn: Build
  displayName: Test on Azure
  jobs:
  - job: Deploy
    displayName: 'Trying to deploy'
    strategy:
      matrix:
        windows:
          image_name: 'windows-latest'
        macos:
          image_name: 'macos-latest'
        ubuntu:
          image_name: 'ubuntu-latest'
    pool:
      vmImage: $(image_name)
    steps:
    - script: |
        echo "hello"
    - powershell: |
        gci env:
      displayName: Go setup debug
